### ISSUE TITLE
Change in-app "Contact Us" email

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-windows8#2]
Per the [multi-region design](https://github.com/OneBusAway/onebusaway/wiki/Multi-Region#contact-info), the main “Contact Us” email that is in-app should be changed to the `contactEmail` field from the [Regions API](regions.onebusaway.org/regions.json) (based on whatever region is currently selected).  

We want to direct the majority of in-app feedback to the region (since feedback tends to be data or agency-related), and then they can forward the app-specific feedback to the main app developer email.

If there is a specific "Contact the developer" email listed somewhere, this email address should be changed to windows-app@onebusaway.org.

**Comment by mbraude** [comment]
I have updated the contact us email address in the latest release for Windows 8.1.
